// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

#include "order.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class makeOrderRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<makeOrderRequest>
      _instance;
} _makeOrderRequest_default_instance_;
class makeOrderResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<makeOrderResponse>
      _instance;
} _makeOrderResponse_default_instance_;
namespace protobuf_order_2eproto {
void InitDefaultsmakeOrderRequestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_makeOrderRequest_default_instance_;
    new (ptr) ::makeOrderRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::makeOrderRequest::InitAsDefaultInstance();
}

void InitDefaultsmakeOrderRequest() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsmakeOrderRequestImpl);
}

void InitDefaultsmakeOrderResponseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_makeOrderResponse_default_instance_;
    new (ptr) ::makeOrderResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::makeOrderResponse::InitAsDefaultInstance();
}

void InitDefaultsmakeOrderResponse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsmakeOrderResponseImpl);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::ServiceDescriptor* file_level_service_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::makeOrderRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::makeOrderRequest, price_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::makeOrderRequest, goods_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::makeOrderResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::makeOrderResponse, ret_code_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::makeOrderResponse, res_info_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::makeOrderResponse, order_id_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::makeOrderRequest)},
  { 7, -1, sizeof(::makeOrderResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_makeOrderRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_makeOrderResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "order.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, file_level_service_descriptors);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013order.proto\"0\n\020makeOrderRequest\022\r\n\005pri"
      "ce\030\001 \001(\005\022\r\n\005goods\030\002 \001(\t\"I\n\021makeOrderResp"
      "onse\022\020\n\010ret_code\030\001 \001(\005\022\020\n\010res_info\030\002 \001(\t"
      "\022\020\n\010order_id\030\003 \001(\t2p\n\005Order\0222\n\tmakeOrder"
      "\022\021.makeOrderRequest\032\022.makeOrderResponse\022"
      "3\n\nqueryOrder\022\021.makeOrderRequest\032\022.makeO"
      "rderResponseB\003\200\001\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 265);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "order.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_order_2eproto

// ===================================================================

void makeOrderRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int makeOrderRequest::kPriceFieldNumber;
const int makeOrderRequest::kGoodsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

makeOrderRequest::makeOrderRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_order_2eproto::InitDefaultsmakeOrderRequest();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:makeOrderRequest)
}
makeOrderRequest::makeOrderRequest(const makeOrderRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  goods_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.goods().size() > 0) {
    goods_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.goods_);
  }
  price_ = from.price_;
  // @@protoc_insertion_point(copy_constructor:makeOrderRequest)
}

void makeOrderRequest::SharedCtor() {
  goods_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  price_ = 0;
  _cached_size_ = 0;
}

makeOrderRequest::~makeOrderRequest() {
  // @@protoc_insertion_point(destructor:makeOrderRequest)
  SharedDtor();
}

void makeOrderRequest::SharedDtor() {
  goods_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void makeOrderRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* makeOrderRequest::descriptor() {
  ::protobuf_order_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_order_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const makeOrderRequest& makeOrderRequest::default_instance() {
  ::protobuf_order_2eproto::InitDefaultsmakeOrderRequest();
  return *internal_default_instance();
}

makeOrderRequest* makeOrderRequest::New(::google::protobuf::Arena* arena) const {
  makeOrderRequest* n = new makeOrderRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void makeOrderRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:makeOrderRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  goods_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  price_ = 0;
  _internal_metadata_.Clear();
}

bool makeOrderRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:makeOrderRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 price = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &price_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string goods = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_goods()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->goods().data(), static_cast<int>(this->goods().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "makeOrderRequest.goods"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:makeOrderRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:makeOrderRequest)
  return false;
#undef DO_
}

void makeOrderRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:makeOrderRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 price = 1;
  if (this->price() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->price(), output);
  }

  // string goods = 2;
  if (this->goods().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->goods().data(), static_cast<int>(this->goods().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "makeOrderRequest.goods");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->goods(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:makeOrderRequest)
}

::google::protobuf::uint8* makeOrderRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:makeOrderRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 price = 1;
  if (this->price() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->price(), target);
  }

  // string goods = 2;
  if (this->goods().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->goods().data(), static_cast<int>(this->goods().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "makeOrderRequest.goods");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->goods(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:makeOrderRequest)
  return target;
}

size_t makeOrderRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:makeOrderRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string goods = 2;
  if (this->goods().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->goods());
  }

  // int32 price = 1;
  if (this->price() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->price());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void makeOrderRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:makeOrderRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const makeOrderRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const makeOrderRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:makeOrderRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:makeOrderRequest)
    MergeFrom(*source);
  }
}

void makeOrderRequest::MergeFrom(const makeOrderRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:makeOrderRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.goods().size() > 0) {

    goods_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.goods_);
  }
  if (from.price() != 0) {
    set_price(from.price());
  }
}

void makeOrderRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:makeOrderRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void makeOrderRequest::CopyFrom(const makeOrderRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:makeOrderRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool makeOrderRequest::IsInitialized() const {
  return true;
}

void makeOrderRequest::Swap(makeOrderRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void makeOrderRequest::InternalSwap(makeOrderRequest* other) {
  using std::swap;
  goods_.Swap(&other->goods_);
  swap(price_, other->price_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata makeOrderRequest::GetMetadata() const {
  protobuf_order_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_order_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void makeOrderResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int makeOrderResponse::kRetCodeFieldNumber;
const int makeOrderResponse::kResInfoFieldNumber;
const int makeOrderResponse::kOrderIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

makeOrderResponse::makeOrderResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_order_2eproto::InitDefaultsmakeOrderResponse();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:makeOrderResponse)
}
makeOrderResponse::makeOrderResponse(const makeOrderResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  res_info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.res_info().size() > 0) {
    res_info_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.res_info_);
  }
  order_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.order_id().size() > 0) {
    order_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.order_id_);
  }
  ret_code_ = from.ret_code_;
  // @@protoc_insertion_point(copy_constructor:makeOrderResponse)
}

void makeOrderResponse::SharedCtor() {
  res_info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  order_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ret_code_ = 0;
  _cached_size_ = 0;
}

makeOrderResponse::~makeOrderResponse() {
  // @@protoc_insertion_point(destructor:makeOrderResponse)
  SharedDtor();
}

void makeOrderResponse::SharedDtor() {
  res_info_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  order_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void makeOrderResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* makeOrderResponse::descriptor() {
  ::protobuf_order_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_order_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const makeOrderResponse& makeOrderResponse::default_instance() {
  ::protobuf_order_2eproto::InitDefaultsmakeOrderResponse();
  return *internal_default_instance();
}

makeOrderResponse* makeOrderResponse::New(::google::protobuf::Arena* arena) const {
  makeOrderResponse* n = new makeOrderResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void makeOrderResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:makeOrderResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  res_info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  order_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ret_code_ = 0;
  _internal_metadata_.Clear();
}

bool makeOrderResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:makeOrderResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 ret_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ret_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string res_info = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_res_info()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->res_info().data(), static_cast<int>(this->res_info().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "makeOrderResponse.res_info"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string order_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_order_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->order_id().data(), static_cast<int>(this->order_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "makeOrderResponse.order_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:makeOrderResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:makeOrderResponse)
  return false;
#undef DO_
}

void makeOrderResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:makeOrderResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 ret_code = 1;
  if (this->ret_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->ret_code(), output);
  }

  // string res_info = 2;
  if (this->res_info().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->res_info().data(), static_cast<int>(this->res_info().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "makeOrderResponse.res_info");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->res_info(), output);
  }

  // string order_id = 3;
  if (this->order_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->order_id().data(), static_cast<int>(this->order_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "makeOrderResponse.order_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->order_id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:makeOrderResponse)
}

::google::protobuf::uint8* makeOrderResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:makeOrderResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 ret_code = 1;
  if (this->ret_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->ret_code(), target);
  }

  // string res_info = 2;
  if (this->res_info().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->res_info().data(), static_cast<int>(this->res_info().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "makeOrderResponse.res_info");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->res_info(), target);
  }

  // string order_id = 3;
  if (this->order_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->order_id().data(), static_cast<int>(this->order_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "makeOrderResponse.order_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->order_id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:makeOrderResponse)
  return target;
}

size_t makeOrderResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:makeOrderResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string res_info = 2;
  if (this->res_info().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->res_info());
  }

  // string order_id = 3;
  if (this->order_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->order_id());
  }

  // int32 ret_code = 1;
  if (this->ret_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->ret_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void makeOrderResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:makeOrderResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const makeOrderResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const makeOrderResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:makeOrderResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:makeOrderResponse)
    MergeFrom(*source);
  }
}

void makeOrderResponse::MergeFrom(const makeOrderResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:makeOrderResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.res_info().size() > 0) {

    res_info_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.res_info_);
  }
  if (from.order_id().size() > 0) {

    order_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.order_id_);
  }
  if (from.ret_code() != 0) {
    set_ret_code(from.ret_code());
  }
}

void makeOrderResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:makeOrderResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void makeOrderResponse::CopyFrom(const makeOrderResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:makeOrderResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool makeOrderResponse::IsInitialized() const {
  return true;
}

void makeOrderResponse::Swap(makeOrderResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void makeOrderResponse::InternalSwap(makeOrderResponse* other) {
  using std::swap;
  res_info_.Swap(&other->res_info_);
  order_id_.Swap(&other->order_id_);
  swap(ret_code_, other->ret_code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata makeOrderResponse::GetMetadata() const {
  protobuf_order_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_order_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

Order::~Order() {}

const ::google::protobuf::ServiceDescriptor* Order::descriptor() {
  protobuf_order_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_order_2eproto::file_level_service_descriptors[0];
}

const ::google::protobuf::ServiceDescriptor* Order::GetDescriptor() {
  return descriptor();
}

void Order::makeOrder(::google::protobuf::RpcController* controller,
                         const ::makeOrderRequest*,
                         ::makeOrderResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method makeOrder() not implemented.");
  done->Run();
}

void Order::queryOrder(::google::protobuf::RpcController* controller,
                         const ::makeOrderRequest*,
                         ::makeOrderResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method queryOrder() not implemented.");
  done->Run();
}

void Order::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), protobuf_order_2eproto::file_level_service_descriptors[0]);
  switch(method->index()) {
    case 0:
      makeOrder(controller,
             ::google::protobuf::down_cast<const ::makeOrderRequest*>(request),
             ::google::protobuf::down_cast< ::makeOrderResponse*>(response),
             done);
      break;
    case 1:
      queryOrder(controller,
             ::google::protobuf::down_cast<const ::makeOrderRequest*>(request),
             ::google::protobuf::down_cast< ::makeOrderResponse*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& Order::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::makeOrderRequest::default_instance();
    case 1:
      return ::makeOrderRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::google::protobuf::Message& Order::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::makeOrderResponse::default_instance();
    case 1:
      return ::makeOrderResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

Order_Stub::Order_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
Order_Stub::Order_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
Order_Stub::~Order_Stub() {
  if (owns_channel_) delete channel_;
}

void Order_Stub::makeOrder(::google::protobuf::RpcController* controller,
                              const ::makeOrderRequest* request,
                              ::makeOrderResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void Order_Stub::queryOrder(::google::protobuf::RpcController* controller,
                              const ::makeOrderRequest* request,
                              ::makeOrderResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
